### ISSUE TITLE
can you provide a sample site?

### ISSUE THREAD

**Issue by matteoredaelli** [stevetweeddale/gatsby-source-git#14]
It would be nice to have a full sample website

Regards
Matteo

**Comment by CanRau** [comment]
Anything I might help you with?

**Comment by stevetweeddale** [comment]
Yeah, I'm not sure this plugin is big enough to warrant a whole example site!

If you've not done it before, I'd recommend following along with the standard [Gatsby tutorial](https://www.gatsbyjs.org/tutorial/). Assuming the baseline level of knowledge you get from that, the README of this project _should_ be fairly self-explanatory (though improvements are welcome!). In fact, you could take the site you built, then move the blog post content into a separate repo and pull it in by replacing `gatsby-source-filesytem` (see [part 5 of the tutorial](https://www.gatsbyjs.org/tutorial/part-five/#source-plugins) with `gatsby-source-git` and updating `gatsby-config.js` accordingly). Everything else should work the same.

But yes, if there's a particular problem you're having one of us can probably give you a pointer.

**Comment by stevetweeddale** [comment]
Gonna close this one out. Feel free to reopen @matteoredaelli if you still need help.
