### ISSUE TITLE
Feature request : Fetching data from private repository

### ISSUE THREAD

**Issue by jay-coditas** [stevetweeddale/gatsby-source-git#16]

**Comment by stevetweeddale** [comment]
Is this [section in the README](https://github.com/stevetweeddale/gatsby-source-git#private-repositories) any help?

**Comment by jay-coditas** [comment]
Oh, overlooked the readme.  In the docs, it says currently private repository not supported.
I went with the readme, unfortunately, it isn't working for some reason,
Works well with the syntax mentioned for public repo
For private, I did the following,
`https://jay-coditas:1234567@github.com/MY-repo`
myuser = jay-coditas
token = 1234567
and didn't work
The log says 
`fatal: repository 'https://github.com/My-repo/' not found`
Thanks Steve

**Comment by jay-coditas** [comment]
Resolved the above issue, I guess the readme needs to be updated for fetching data from a private repository.
I tried this, as mentioned in readme
`    remote: `https://myuser:${process.env.GITHUB_TOKEN}@github.com/my-repo`,`
I had to add in (myuser),
`    remote: `https://myuser:${process.env.GITHUB_TOKEN}@github.com/myuser/my-repo`,`

Worked like a charm, 
Thanks for the plugin, really helps,
One last concern,
I followed the doc for giving out other location rather than pushing data in cache,
For some reason, the data is being dumped in cache but not the custom local folder
`local: `${__dirname}/content/repo-one``

**Comment by stevetweeddale** [comment]
Ah, the example github URL not being correct isn't helpful is it. Corrected now.
