### ISSUE TITLE
this package should be on NPM

### ISSUE THREAD

**Issue by leonardodino** [stevetweeddale/gatsby-source-git#2]
Hey Stephen! (:

I know we can install packages directly from git, and I'm [using it](https://github.com/campus-online/frontend/blob/master/package.json#L35) right now,
but it makes me uneasy that there's not a immutable/versioned/canonical distribution.

maybe @theresama can transfer you the package name, it seems to be unused right now.

**Comment by CanRau** [comment]
They seem to collaborate https://www.npmjs.com/package/gatsby-source-git 😉

**Comment by stevetweeddale** [comment]
Yeah, I had to go through the namespace dispute process. But it's been up for a while now, and seems like people are finding it OK.
