### ISSUE TITLE
any advice on auto pull from repository?

### ISSUE THREAD

**Issue by xiaoguilan** [stevetweeddale/gatsby-source-git#23]
hi，there:
   Is there any way to set up such that it listens for updates from responsitory and will pull whenever something changes? 
Or any advice?

**Comment by stevetweeddale** [comment]
Are you talking about running locally in dev mode, or are you talking about running production deploys triggered by changes in the remote repo?

**Comment by xiaoguilan** [comment]
@stevetweeddale 
 Thanks , Is there any difference? In dev mode, what should i do ? And What about the production mode

Thanks again!

**Comment by stevetweeddale** [comment]
Very much so! I'm not sure there's anything that will keep a local git repository in sync with a remote one in real-time (which is what we'd be talking about for the local dev case), so I don't think 'listening' for changes and refreshing content in dev is possible. Personally, I just restart my `gatsby develop` command to pull in fresh changes.

For deploys though, if you're using a git host that supports webhooks, and a CI/CD service that can listen for such notifications, then you should be able to wire them up. So for example, I believe you could configure Github to ping a Netlify build hook URL whenever there's a new commit to master.

**Comment by jidicula** [comment]
> So for example, I believe you could configure Github to ping a Netlify build hook URL whenever there's a new commit to master.

Yes, I can confirm this works, I've done it on jidicula/jidicula-resume to  trigger  a Netlify build of jidicula/forcepush
