### ISSUE TITLE
Looks valuable beyond gatsby

### ISSUE THREAD

**Issue by mrquincle** [stevetweeddale/gatsby-source-git#28]
Hi, this looks like a valuable module for any react-based server, for example nextjs. Would it be too weird to consider that? :-)

**Comment by stevetweeddale** [comment]
Umm, what would be the use case you're imagining? At the moment everything here runs on a gatsby hook (`sourceNodes `), and we just clone the repo locally, then create nodes in gatsby's data graph for the files. I guess if nextjs had a similar hook then the "clone a repo locally" portion could have it's gatsby-assumptions factored out to be made reusable. But it's not doing a whole lot over and above just using [simple-git](https://github.com/steveukx/git-js) to clone the repo.

**Comment by mrquincle** [comment]
Hi, I guess you're right. It would kind of get down to the use of `simple-git` indeed. Will close!
