### ISSUE TITLE
Is the project active maintained?

### ISSUE THREAD

**Issue by BenRoe** [stevetweeddale/gatsby-source-git#38]
Hello @stevetweeddale,
thanks for this useful gatsby plugin. I use it on my documentation site.
Some great features are waiting in the Pull requests list like #12 #26.
Can you merge this PR? If you need help with testing, let me know.

Greetings Ben

**Comment by BenRoe** [comment]
@lawrenceching how can i use your code #26 without manual copy past? Right now i installed the plugin with `npm install --save gatsby-source-git`

**Comment by lawrenceching** [comment]
> @lawrenceching how can i use your code #26 without manual copy past? Right now i installed the plugin with `npm install --save gatsby-source-git`

Unfortunately I can't see a way to do it.
So far I maintain my own copy of gatsby-source-git in my personal project.
[Unfortunately](https://github.com/lawrenceching/imlc.me)

**Comment by lawrenceching** [comment]
Hi @stevetweeddale ,
Same question here.
Could you let us know if you're still maintaining this project?

I'm happy to see any of your feedback for my PR. Even a simple "No" is way better than no reply.

BR,
Lawrence

**Comment by BenRoe** [comment]
> > @lawrenceching how can i use your code #26 without manual copy past? Right now i installed the plugin with `npm install --save gatsby-source-git`
> 
> Unfortunately I can't see a way to do it. So far I maintain my own copy of gatsby-source-git in my personal project, like this: https://github.com/lawrenceching/imlc.me
> 
> Well, as this project does not update anything for so long, maintaining a local copy is not that bad actually... = =!

Thanks for the hint with the local copy.
This helps short term.
Long term we could check how to do fork and add it to npm with a different name.

A short reply from @stevetweeddale would be great, even a no.

**Comment by stevetweeddale** [comment]
Hi everyone,

Yeah I'm sorry I've been AWOL on this. My original motivation for this project was as part of a work project, and I've subsequently moved to a new role and company. Initially, I thought I'd try to maintain this in my free time but a few months down the line it's clear it could use more attention than I'm currently able to give it.

Does anyone have time and interest in becoming a maintainer?

**Comment by BenRoe** [comment]
> Hi everyone,
> 
> Yeah I'm sorry I've been AWOL on this. My original motivation for this project was as part of a work project, and I've subsequently moved to a new role and company. Initially, I thought I'd try to maintain this in my free time but a few months down the line it's clear it could use more attention than I'm currently able to give it.
> 
> Does anyone have time and interest in becoming a maintainer?

Thank you for your honest reply.
I could maintain it, but need some help with reviewing PR. @lawrenceching are you interested to help me, or do you wanna maintain the project?

**Comment by lawrenceching** [comment]
Hi @stevetweeddale , 
Than you for your reply. 
I fully understand your situation. Maintaining an open source project has never been easy.

@BenRoe ,
I can't be a maintainer as I'm rather busy on week day. But, I could definitely help on review PR or maintain doc or something like that.

**Comment by BenRoe** [comment]
Ok then i can try to maintain the Repo. 
@stevetweeddale you can keep the ownership and give us some permission to accept PR,
or you transfer the ownership to me.

**Comment by itsmejoeeey** [comment]
> Unfortunately I can't see a way to do it.
So far I maintain my own copy of gatsby-source-git in my personal project, like this:
https://github.com/lawrenceching/imlc.me
>
> Well, as this project does not update anything for so long, maintaining a local copy is not that bad actually... = =!

FYI for anyone else coming across this thread - [it is possible to directly `npm install` a PR](https://stackoverflow.com/a/36743127/3213602). The following works to install @lawrenceching's PR that adds the `enableShallowClone` option:
```
npm install stevetweeddale/gatsby-source-git#pull/26/head
```

**Comment by iloveip** [comment]
Hi @stevetweeddale,

Do you have any update on switching ownership of this repository to some one else? It's the only source plugin for GitHub, but when I try to reinstall it I get some critical errors.

`10 vulnerabilities (4 moderate, 4 high, 2 critical)`

**Comment by darthsteven** [comment]
Hi @iloveip 

I also have access to maintain the repo, I'll look at getting dependabot going on the repo again and generally getting things into a better state. Stay tuned!

**Comment by iloveip** [comment]
Hi @darthsteven

That would be great! Thank you very much! I also look forward to merging #26 🙏

**Comment by darthsteven** [comment]
I committed some things!
Still much more work to do, I'm going to close this issue out because we are now being maintained, but I appreciate that until I cut some releases it won't really _feel_ like that.

**Comment by darthsteven** [comment]
@iloveip not yet! I'm just trying to resolve some issues around caching as brought up in #46 and then I'll cut a release and get it published on npm.

**Comment by iloveip** [comment]
@darthsteven Ok
, thank you very much for your reply 🙏 I will be looking forward to it.
