### ISSUE TITLE
Create and publish a new release.

### ISSUE THREAD

**Issue by darthsteven** [stevetweeddale/gatsby-source-git#52]
Time for a 2.0.0.

**Comment by darthsteven** [comment]
@stevetweeddale I'm going to need your help publishing the package on npmjs.com, I've got a beta release tagged, but no permissions to publish on npm :)
My username over there is [darthsteven](https://www.npmjs.com/~darthsteven).

**Comment by darthsteven** [comment]
The beta version is out! https://www.npmjs.com/package/gatsby-source-git/v/2.0.0-beta.0

**Comment by iloveip** [comment]
@darthsteven Thank you very much for your work! 😍
