### ISSUE TITLE
Processing remote images

### ISSUE THREAD

**Issue by macdonst** [stevetweeddale/gatsby-source-git#6]
Hey @stevetweeddale, thanks for working on this plugin. I just started playing around with it and I can convert all of my remote .md files from github nicely but I'm having issues with the images. Do you have any examples or hints there?

**Comment by macdonst** [comment]
Heh, well since I opened this an hour ago I found out that I should be adding a plugin to `gatsby-transformer-remark`.

```
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: "gatsby-remark-images",
            options: {
              maxWidth: 970,
            },
          },
        ],
      },
    },
```

This is working great now, except when I deploy to gh-pages. For some reason my prefix path doesn't get applied.

**Comment by stevetweeddale** [comment]
Glad you worked it out! The "hint" is simply to "do whatever you would do if the files were local and you'd sourced them in the normal way with gatsby-source-filesystem". That's all this plugin does; it clones clone the repo (so your "remote" files become local) and then inserts nodes into the graph that look like gatsby-source-filesystem put them there. So you can follow all the normal tutorials that assume you're using gatsby-source-filesystem and it should just work.

> This is working great now, except when I deploy to gh-pages. For some reason my prefix path doesn't get applied.

This doesn't sound like an issue with this plugin at all to me, so I'm going to close this issue if that's OK. [the gatsby community page](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) has some suggestions of good places to go for general support using Gatsby.

**Comment by macdonst** [comment]
@stevetweeddale yeah, sorry I meant to come back and close this issue. The image file path problem resolution just in case anyone comes across this issue was a problem with Gatsby. I did a `gatsby build` to test locally then a `gastby build --prefix-paths` before deploying to github. Because nothing had changed the files pulled from github didn't have the paths to the image updated. Clearing the cache and rebuilding fixed it.
