### ISSUE TITLE
Unable to use gatsby environment variable with gataby-source-git patterns

### ISSUE THREAD

**Issue by hirenoble** [stevetweeddale/gatsby-source-git#8]
Gatsby-source-git plugin expects the patterns to be defined as [\`\*\`, \`!\*.md\`] (without grave accent symbols) where as gatsby environment variable inserts the patterns as \`[\`\*\`, \`!\*.md\`]\`

Steps to reproduce
gatsby-config.js
{
resolve: gatsby-source-git,
options: {
name: ``,
remote: ${process.env.GATSBY_SOURCE},
// Optionally supply a branch. If none supplied, you'll get the default branch.
branch: `${process.env.GATSBY_SOURCE_BRANCH}`,
// Tailor which files get imported eg. import the docs folder from a codebase.
patterns: process.env.GATSBY_SOURCE_PATTERNS,
},
},

Expected result
Source files from Github repository as per the patterns.
The build should complete successfully.

Actual result
Because of extra `` the patterns are not recognized and the build fails.

Environment
Production

**Comment by CanRau** [comment]
That's because the options expects an actual array `[]` and not a string `''`

What's the reason you can't set `patterns: ['*', '!*.md']`?
Maybe there's another solution

If not you could
1st. If the first will always be `*` and you want to change only the second via your env var
```js
patterns: ['*', process.env.GATSBY_SOURCE_PATTERNS]
```
or
2nd. define 2 env vars like so
```js
patterns: [
  process.env.GATSBY_SOURCE_PATTERNS_1,
  process.env.GATSBY_SOURCE_PATTERNS_2
]
```
You can of course name them however makes sense to you 😉

**Comment by hirenoble** [comment]
Hi CanRau,

Thanks for your prompt response, the reason is that I'm taking the patterns from the user via a form and setting the gatsby environment variable. 

The patterns can be dynamic i.e. one to many and different ones

Defining patterns like this would be ugly :( in my case.
`
patterns: [
  process.env.GATSBY_SOURCE_PATTERNS_1,
  process.env.GATSBY_SOURCE_PATTERNS_2
]
`

**Comment by hirenoble** [comment]
In my opinion, the gatsby-source-git patterns should accept: \`[\*, !\*.md, \*.json]\` as input and later in the code we can interpret the string as an array input.

**Comment by CanRau** [comment]
Hm in a form? So you're setting up some kind of page builder?
There's no other option than passing the patterns via env?
Where do they come from?

Uh another way would be to parse the string yourself so if your env var is proper JSON like so
```bash
GATSBY_SOURCE_PATTERNS = '["*", "!*.md"]'
```
then you could in your gatsby-config.js
```js
const patterns = JSON.parse(process.env.GATSBY_SOURCE_PATTERNS)
module.exports = {
  plugins: [
    {
      resolve: gatsby-source-git,
      options: {
        patterns,
      },
    },
  ].
}
```
But make sure that string is **proper JSON**, if you can't be sure you're maybe better off using something like
```bash
# just a comma or whatever delimited string
# !!has to be something people wouldn't use in their patterns!!!
# so maybe use ',,,,' multiple commas or whatever
GATSBY_SOURCE_PATTERNS = '*,!*.md'
```
then you could in your gatsby-config.js
```js
const patterns = process.env.GATSBY_SOURCE_PATTERNS.split(',') // or whatever your delimiter is
module.exports = {
  plugins: [
    {
      resolve: gatsby-source-git,
      options: {
        patterns,
      },
    },
  ].
}
```

I think I'd find another way entirely instead of env vars if possible

**Comment by CanRau** [comment]
> In my opinion, the gatsby-source-git patterns should accept: `[*, !*.md, *.json]` as input and later in the code we can interpret the string as an array input.

That could work yet depends on the maintainer @stevetweeddale agreeing and would take longer for you until it's been implemented 😉 
And as most Gatsby plugins I know accept "normal" JS values and don't parse strings I'm not sure about that one, cause it adds extra complexity for the plugin.

**Comment by hirenoble** [comment]
@CanRau there is no other way than Gatsby Environment Variable. I like this approach and would test it out:

```const patterns = process.env.GATSBY_SOURCE_PATTERNS.split(',') // or whatever your delimiter is
module.exports = {
  plugins: [
    {
      resolve: gatsby-source-git,
      options: {
        patterns,
      },
    },
  ].
}```

**Comment by hirenoble** [comment]
@CanRau It worked like charm! Thank you very much :)

**Comment by CanRau** [comment]
@hirenoble you're welcome 👍  glad it worked for you 🎉

**Comment by CanRau** [comment]
@hirenoble I think you could close this issue if you're happy with that solution?
